#!/usr/bin/env python3
import os
import sys
import subprocess
from pathlib import Path

# ANSI colors helper
def color_print(text, color="white"):
    colors = {
        "green": "\033[0;32m",
        "red": "\033[0;31m",
        "yellow": "\033[0;33m",
        "blue": "\033[0;34m",
        "cyan": "\033[0;36m",
        "white": "\033[0m"
    }
    if os.name == 'nt':  # Windows command prompt colors workaround
        print(text)
    else:
        print(f"{colors.get(color, colors['white'])}{text}\033[0m")

def get_pio_path():
    bin_dir = Path(sys.executable).parent
    pio_name = "pio.exe" if os.name == "nt" else "pio"
    pio_path = bin_dir / pio_name
    if pio_path.exists():
        return str(pio_path)
    return "pio"

def get_serial_ports():
    try:
        import serial.tools.list_ports
        return list(serial.tools.list_ports.comports())
    except ImportError:
        color_print("Warning: pyserial is not available. Port autodetect disabled.", "yellow")
        return []

def select_port():
    ports = get_serial_ports()
    if not ports:
        return input("Please enter the serial port path manually (e.g. /dev/ttyUSB0 or COM3): ").strip()
    
    color_print("\nDetected serial ports:", "cyan")
    for idx, port in enumerate(ports, 1):
        desc = f" - {port.description}" if port.description else ""
        print(f"  {idx}) {port.device}{desc}")
    print(f"  {len(ports) + 1}) Enter port manually")
    
    while True:
        try:
            choice = input(f"Select a port (1-{len(ports) + 1}): ").strip()
            if not choice:
                continue
            val = int(choice)
            if 1 <= val <= len(ports):
                return ports[val - 1].device
            elif val == len(ports) + 1:
                return input("Please enter the serial port path manually: ").strip()
        except ValueError:
            pass
        print(f"Invalid selection. Please choose between 1 and {len(ports) + 1}.")

def ask_yes_no(question, default="y"):
    options = "[Y/n]" if default.lower() == "y" else "[y/N]"
    val = input(f"{question} {options}: ").strip().lower()
    if not val:
        val = default.lower()
    return val in ["y", "yes"]

def run_npm_install():
    color_print("\n=== Installing Webapp Frontend Dependencies ===", "blue")
    webapp_dir = Path(__file__).resolve().parent / "webapp"
    try:
        # Use shell=True for windows npm compatibility
        subprocess.run(["npm", "install"], cwd=webapp_dir, shell=True, check=True)
        color_print("Frontend dependencies installed successfully!", "green")
    except Exception as e:
        color_print(f"Error installing frontend dependencies: {e}", "red")
        color_print("You may need to run 'npm install' inside the webapp/ directory manually.", "yellow")

def flash_firmware(device_name, directory, env_name):
    color_print(f"\n--- Preparing to flash {device_name} ---", "cyan")
    if not ask_yes_no(f"Do you want to flash {device_name}?"):
        color_print(f"Skipped {device_name}.", "yellow")
        return

    port = select_port()
    if not port:
        color_print("No port selected. Skipping flashing.", "yellow")
        return

    pio_path = get_pio_path()
    cmd = [
        pio_path, "run",
        "-d", str(directory),
        "-e", env_name,
        "--target", "upload",
        "--upload-port", port
    ]
    
    color_print(f"Running PlatformIO command: {' '.join(cmd)}", "blue")
    try:
        subprocess.run(cmd, check=True)
        color_print(f"Successfully flashed {device_name} on {port}!", "green")
    except subprocess.CalledProcessError as e:
        color_print(f"Failed to flash {device_name}. Error code: {e.returncode}", "red")
        if ask_yes_no("Would you like to try flashing this device again?"):
            flash_firmware(device_name, directory, env_name)

def generate_launch_scripts():
    color_print("\n=== Generating Startup Launcher Scripts ===", "blue")
    root_dir = Path(__file__).resolve().parent

    # Linux/Mac Script
    sh_content = f"""#!/bin/bash
# Automatically generated by ChArm setup wizard
export CHARM_PYTHON="$(pwd)/venv/bin/python"
cd webapp
npm run dev
"""
    sh_path = root_dir / "start.sh"
    try:
        sh_path.write_text(sh_content, encoding="utf-8")
        os.chmod(sh_path, 0o755)
        color_print(f"Created executable start.sh launcher in root.", "green")
    except Exception as e:
        color_print(f"Could not create start.sh: {e}", "red")

    # Windows Script
    bat_content = r"""@echo off
:: Automatically generated by ChArm setup wizard
set CHARM_PYTHON=%~dp0venv\Scripts\python.exe
cd webapp
npm run dev
"""
    bat_path = root_dir / "start.bat"
    try:
        bat_path.write_text(bat_content, encoding="utf-8")
        color_print("Created start.bat launcher in root.", "green")
    except Exception as e:
        color_print(f"Could not create start.bat: {e}", "red")

def print_help_tips():
    if os.name != 'nt':
        color_print("\n=== Linux/macOS Permissions Note ===", "yellow")
        color_print("If PlatformIO fails to upload because of serial port permission issues,", "yellow")
        color_print("make sure your user belongs to the 'dialout' (or 'uucp') group.", "yellow")
        color_print("Example command: sudo usermod -a -G dialout $USER", "yellow")
        color_print("You may need to log out and log back in for changes to take effect.", "yellow")
    else:
        color_print("\n=== Windows Serial Drivers Note ===", "yellow")
        color_print("Ensure you have installed the correct USB-to-UART drivers (e.g. CP210x or CH340)", "yellow")
        color_print("for your boards so that they show up as COM ports in Device Manager.", "yellow")

def main():
    color_print("=============================================", "green")
    color_print("    ChArm Setup & Installation Wizard        ", "green")
    color_print("=============================================", "green")
    
    root_dir = Path(__file__).resolve().parent
    
    # 1. Install NPM frontend packages
    if ask_yes_no("Would you like to install Node.js/NPM dependencies for the webapp frontend?"):
        run_npm_install()
    
    # 2. Hardware firmware flashing
    if ask_yes_no("Would you like to flash firmware to your hardware devices?"):
        # ESP32 CAM
        flash_firmware(
            device_name="ESP32 CAM (Mega Bridge)",
            directory=root_dir / "arduino_code" / "esp32_cam_mega_bridge",
            env_name="esp32cam"
        )
        
        # ESP32 UI Box
        flash_firmware(
            device_name="ESP32 UI Box",
            directory=root_dir / "arduino_code" / "esp32_ui_box",
            env_name="esp32_ui_box"
        )
        
        # Arduino Mega
        flash_firmware(
            device_name="Arduino Mega 2560",
            directory=root_dir / "arduino_code",
            env_name="megaatmega2560"
        )
        
        print_help_tips()

    # 3. Create startup shortcuts
    generate_launch_scripts()
    
    color_print("\nSetup configuration finished! To launch the webapp, run:", "green")
    if os.name == 'nt':
        color_print("  start.bat", "cyan")
    else:
        color_print("  ./start.sh", "cyan")
    color_print("=============================================", "green")

if __name__ == "__main__":
    main()
