; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
    arduino-libraries/Servo
    Arduino-Libraries/LiquidCrystal
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF
build_src_filter = +<**/*> -<main2.cpp> -<main_button_lcd.cpp> -<main_lcd_test.cpp> -<main_ui_test.cpp> -<main_sim_test.cpp>

[env:debug_limit]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    arduino-libraries/Servo
    Arduino-Libraries/LiquidCrystal
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF
build_src_filter = +<**/*> -<main.cpp> -<main_button_lcd.cpp> -<main_lcd_test.cpp> -<main_ui_test.cpp> -<main_sim_test.cpp>

[env:button_lcd_test]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    arduino-libraries/Servo
    Arduino-Libraries/LiquidCrystal
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF
build_src_filter = +<**/*> -<main.cpp> -<main2.cpp> -<main_lcd_test.cpp> -<main_ui_test.cpp> -<main_sim_test.cpp>

[env:lcd_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    arduino-libraries/Servo
    Arduino-Libraries/LiquidCrystal
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF
build_src_filter = +<**/*> -<main.cpp> -<main2.cpp> -<main_button_lcd.cpp> -<main_ui_test.cpp> -<main_sim_test.cpp>

[env:ui_test]
platform = atmelavr
board = uno
framework = arduino
upload_port = /dev/cu.usbserial-120
upload_speed = 115200
lib_deps =
    arduino-libraries/Servo
    Arduino-Libraries/LiquidCrystal
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF
build_src_filter = +<**/*> -<main.cpp> -<main2.cpp> -<main_button_lcd.cpp> -<main_lcd_test.cpp> -<main_sim_test.cpp>

[env:sim_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    arduino-libraries/Servo
    Arduino-Libraries/LiquidCrystal
monitor_speed = 115200
monitor_filters = direct
monitor_echo = yes
monitor_eol = LF
build_src_filter = +<**/*> -<main.cpp> -<main2.cpp> -<main_button_lcd.cpp> -<main_lcd_test.cpp> -<main_ui_test.cpp>
